### ISSUE TITLE
Garbled depth images

### ISSUE THREAD

**Issue by IanKirwan** [umautobots/GTAVisionExport#28]
Hiya, I'm getting garbled depth images out from the managed tool (example below). I have MSAA turned off, and for reflections too. Window resolution 1280x720, all of the graphics settings turned down to 'normal'. Any clues as to how I might resolve this? PS stencil looks like its garbled too.

![45871](https://user-images.githubusercontent.com/29286097/35881174-dcfe4a0e-0b77-11e8-97b1-15776673c108.jpg)
Used the following code to display the depth in Python:
```
from PIL import Image, ImageFile, TiffImagePlugin
import numpy as np
import cv2
ImageFile.LOAD_TRUNCATED_IMAGES = True
TiffImagePlugin.READ_LIBTIFF = True

im = Image.open('D:/Snapshots/Output/45871.tiff') # with your own image path.
im.seek(1) # use seek() to switch between pages
image = np.array(im.getdata()).reshape(im.size[1], im.size[0], 1)
maximg = np.max(image)
imageint = (image/maximg)*255

print(im.size[0])
print(im.size[1])
cv2.imshow('img',imageint)
cv2.waitKey(0)
```

**Comment by IanKirwan** [comment]
If someone could zip up a working (for depth maps) 64bit GTAVisionNative.asi and GTAVisionNative.lib and post it here that would be a huge help.
Many thanks in advance.

**Comment by Cuky88** [comment]
Hey, I was about to open this issue, too! 
I have 2 workstations, one with a single GTX 1060Ti and one with 2x GTX 1080Ti GPU. On host with one GPU, the depth and stencil works fine, but on the computer with 2 GPUs I have the same issues as Ian.

Any idea why this happens?

Here is the native I use on both computers.
[native64bit.zip](https://github.com/umautobots/GTAVisionExport/files/1703454/native64bit.zip)

**Comment by IanKirwan** [comment]
Thanks @Cuky88,

I'll give your build a try on mine now and let you know what happens.

**Comment by IanKirwan** [comment]
OK, I'm getting the same issue using your GTAVNative build. I'm using a GTX 970 here, and a 1080ti at work. I'll try this on the 1080ti. I'm guessing I'll get the same result as you for your dual 1080ti system.

**Comment by Cuky88** [comment]
The eigen3 versions are the same on both computers. I did build the asi on host with 2 GPUs and tried on both computers. On host with 1 GPU everything works fine.  I also build the asi on host with 1 GPU and tried on both host, but the results were the same.

**Comment by IanKirwan** [comment]
Yeah. Looking like a GPU problem then. I'm afraid I don't have the
knowledge to solve this in a timely manner. Might have to switch to using
Carla until this sorted.

On 7 Feb 2018 3:51 p.m., "Selcuk Aklan" <notifications@github.com> wrote:

The eigen3 versions are the same on both computers. I did build the asi on
host with 2 GPUs and tried on both computers. On host with 1 GPU everything
works fine. I also build the asi on host with 1 GPU and tried on both host,
but the results were the same.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/umautobots/GTAVisionExport/issues/28#issuecomment-363812749>,
or mute the thread

**Comment by dominikandreas** [comment]
I've noticed that the buffer size (resolution) for the depth/stencil map varies with GTA version/GPU/driver used. So the extracted buffers could be valid, but the way they are converted to images is not. If buffers really seem completely garbage, it's usually bc of some graphics setting like AA. Try to export the buffers manually using the native plugin (write with "wb" not "w" as done in the source code) and load them in python with numpy.frombuffer to figure out how to convert them to an image correctly.

**Comment by IanKirwan** [comment]
Hi @dominikandreas ,
Please excuse my ignorance. How will writing the files as binary help? Is that purely so they can be read in Python? 
I've had MSAA switched off as per instructions here. Might try swtching it on as a quick test.
I have been trying to read the raw file using Matlab (code below). The intermediate variable I shows the file to contain an awful lot of 0s, which I understand to be NaNs, with series of real values interlaced.
```
clc;
close all;
clear all;

if true
    row=720; col=1280; ch = 3;
  % row=1024;  col=1024;
fin=fopen('C:\Program Files\Rockstar Games\Grand Theft Auto V\color.raw','r');
fin=fopen('C:\Program Files\Rockstar Games\Grand Theft Auto V\depth.raw','r');

% I=fread(fin,row*col,'uint8=>uint8'); 
I=fread(fin,row*col,'single'); 
maxI = max(I(:))
imgDepthShow = uint8(255*I/maxI); % scale the image to use imshow
Z=reshape(imgDepthShow,[col, row]);

Z=Z';
k=imshow(Z)
end
```

**Comment by Cuky88** [comment]
I'm trying to convert the buffer into an image right now. But need more time to understand how it was done in the native. I used this code in python:
```
import numpy as np 
import cv2

depthBuf = open('depth.raw', 'rb')
d = np.fromfile(depthBuf)
print(d) # len(d) = 460.800 
```
This is the depth.raw I use.
[depth.zip](https://github.com/umautobots/GTAVisionExport/files/1704250/depth.zip)

**Comment by dominikandreas** [comment]
If you want to read it as binary (using "rb") you have to save it as binary
as well. I didn't want to make any assumptions on what happens if you
don't, so I chose to write it in binary mode as well (using "wb") to get
back the exact same data without any encoding issues.

**Comment by IanKirwan** [comment]
Hi @dominikandreas ,

Could you post up your exact GTAV graphics settings?
Switching MSAA on just made the depth buffer all zeros.
For info the garbled depth map appears to only contain information about the upper half of the scene.

**Comment by Cuky88** [comment]
Issue is fixed, when I activated MSAA, run the mod, then deactivated it and also deactivated Vsync. Now everything is fine. No need to try to convert buffer into numpy array

**Comment by IanKirwan** [comment]
@Cuky88
Do you mean the 'wb' mod suggested by Dominik?

On 7 Feb 2018 7:23 p.m., "Selcuk Aklan" <notifications@github.com> wrote:

Issue is fixed, when I activated MSAA, run the mod, then deactivated it and
also deactivated Vsync. Now everything is fine. No need to try to convert
buffer into numpy array

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/umautobots/GTAVisionExport/issues/28#issuecomment-363881298>,
or mute the thread

**Comment by Cuky88** [comment]
I tried to implement Dominik's suggestion, but I couldn't manage to properly reshape the binary array, so that I get an useful depth image. Then in GTA graphic settings I saw that Vsync was on, so I turned it off and now the depth buffer works. No need to do anything further.

[Data.zip](https://github.com/umautobots/GTAVisionExport/files/1704601/Data.zip)

**Comment by IanKirwan** [comment]
Hmm I tried turning off vsync earlier but did not work but can't remember
if I had msaa switched on. Will try it again when I get back home.

**Comment by IanKirwan** [comment]
No good for me. Turned off msaa and vsync and restarted GTAV. Still getting garbled depth in my tiff files.
Will have to try Dominik's suggestion.

**Comment by Cuky88** [comment]
Did you turn off every setting with an "AA" in it?

**Comment by IanKirwan** [comment]
@Cuky88 
How did you create those tiffs? Did you extract them from the multilayer tiff produced by the managed code or from the individual color, depth and stencil files produce by the native code?

**Comment by IanKirwan** [comment]
Yes, all anti-aliasing is off, FXAA, MSAA and MSAA reflections.

**Comment by Cuky88** [comment]
The tiffs are from the managed code. I don't save multi paged tiffs, since I cannot open them in python.
HUD and radar are off, too?

**Comment by IanKirwan** [comment]
Yeah hud radar and GPS are off. I'll try all of this on the 1080ti
tomorrow. Maybe I'll have better luck with that.

**Comment by dominikandreas** [comment]
Fyi my settings are all on minimum values. Resolution is at 800x600. When
reading depth files with numpy, try using np.frombuffer(filecontent,
dtype="float32").reshape(height, width). In my case depth buffer has 32bits
per pixel, that's why I'm using float32, works for me.

**Comment by IanKirwan** [comment]
Thanks Dominik. I'll try out your suggestions and settings tomorrow.

**Comment by IanKirwan** [comment]
Tried managed code on my works machine with a 1080ti and it worked with minimal settings though was still able to capture depth at 1280x720. It's not working on my home machine but that's OK. Probably wouldnt be able to train a depth estimator on my GTX970 anyway. Might still try Dominik's suggestions.

**Comment by IanKirwan** [comment]
Cant quite fathom the depth raw (binary format using 'wb') file. I'm capturing at 1280x720 but the file size is 11289600. Divided by 1280x720 gives 12.25 bytes per pixel. Example:

[depth.zip](https://github.com/umautobots/GTAVisionExport/files/1708586/depth.zip)

**Comment by dominikandreas** [comment]
As I mentioned before, the buffers are sometimes rendered at higher resolutions. In your case it could be 1.75 times your actual resolution, leading to an actual resolution of 2240x1260 and giving 2240*1260*4 = 11289600

**Comment by dominikandreas** [comment]
using the file you uploaded, the following works for me:

```python
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

with open("depth.raw", "rb") as f:
    buffer = f.read()
    
im = np.frombuffer(buffer, dtype="float32").reshape(int(720*1.75), -1)
plt.imshow(im)
plt.axis("off");
```
result:
![](https://i.imgur.com/0h1wZWjl.png)

**Comment by IanKirwan** [comment]
You nailed it. Thanks for spoon feeding me. Much appreciated.

**Comment by IanKirwan** [comment]
Managed to do it with:
```
with open('C:\Program Files\Rockstar Games\Grand Theft Auto V\depth.raw', 'rb') as file:
    depthBuf = file.read()
    
depth = np.frombuffer(depthBuf, dtype=np.float32) 
image = np.reshape(depth, (1260, 2240), 'C')
image=cv2.resize(image, (1280, 720))
maximg = np.max(image)
print(maximg)
imageint = image*100#(image/maximg)*255
cv2.imshow('img',imageint)
cv2.waitKey(0)
```
Will probably hack the native/managed code as a one off for my 970 this weekend.

**Comment by IanKirwan** [comment]
FYI @barcharcraz

**Comment by IanKirwan** [comment]
FYI @barcharcraz 
See pull request #31

**Comment by yipengm** [comment]
@IanKirwan I have been struggling on generating the raw for two weeks. I turned off all the 'AA', radar and GPS as you discussed.  But I still cannot generate a .raw file like you uploaded. I was testing using 
dominikandreas's code:
> import numpy as np
> from matplotlib import pyplot as plt
> %matplotlib inline
> 
> with open("depth.raw", "rb") as f:
>     buffer = f.read()
>     
> im = np.frombuffer(buffer, dtype="float32").reshape(int(720*1.75), -1)
> plt.imshow(im)
> plt.axis("off");

But it turns out:`ValueError: buffer size must be a multiple of element size`
I also tried Cuky88's native64bit but it doesn't work.

Can I have your 64bit GTAVisionNative.asi and GTAVisionNative.lib? Thank you very much
